[workspace]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[dependencies]
bedtools = "*"
python = ">=3.10,<3.13"
zlib = "*"

[pypi-dependencies]
pylbsr = { path = ".", editable = true }

[feature.dev.pypi-dependencies]
pylbsr = { path = ".", editable = true, extras = ["dev"] }

[feature.torch.pypi-dependencies]
pylbsr = { path = ".", editable = true, extras = ["torch"] }

[environments]
default = { features = ["dev"], solve-group = "default" }
bare = { solve-group = "default" }
torch = { features = ["torch"], solve-group = "default" }

[tasks]
test = "pytest"
